# Generated by Django 5.0 on 2023-12-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='FIO_customer',
            field=models.CharField(default='FIO', max_length=255, null=True, verbose_name='ФИО покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адресс доставки'),
        ),
        migrations.CreateModel(
            name='Pos_parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение характеристики')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.parametr', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Позиция характеристики',
                'verbose_name_plural': 'Позиции характеристик',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('update_data', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография товара')),
                ('exists', models.BooleanField(default=True, verbose_name='Продается ли на данный момент?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.category')),
                ('parametr', models.ManyToManyField(through='magazine.Pos_parametr', to='magazine.parametr')),
                ('tag', models.ManyToManyField(blank=True, to='magazine.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Pos_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.supply', verbose_name='Поставка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
        migrations.AddField(
            model_name='pos_parametr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество продукта')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка на продукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='magazine.Pos_order', to='magazine.product'),
        ),
        migrations.AddField(
            model_name='supply',
            name='product',
            field=models.ManyToManyField(through='magazine.Pos_supply', to='magazine.product', verbose_name='Товары'),
        ),
    ]
