# Generated by Django 5.0 on 2024-01-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_category_tag_alter_order_options_remove_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('change_address', 'Возможность изменения адреса поставщика')], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
